import re, urllib.request, os
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rizo", "fonts"))
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
fams = [
  ("bricolage-grotesque", "Bricolage+Grotesque:opsz,wght@12..96,400..800"),
  ("literata", "Literata:ital,opsz,wght@0,7..72,400..700;1,7..72,400..700"),
  ("space-mono", "Space+Mono:ital,wght@0,400;0,700;1,400;1,700"),
]
out = ["/* Bundled fonts (SIL Open Font License 1.1, see OFL-*.txt). Generated by getfonts.py. */"]
for slug, q in fams:
    css = urllib.request.urlopen(urllib.request.Request(f"https://fonts.googleapis.com/css2?family={q}&display=swap", headers={"User-Agent": UA})).read().decode()
    for subset, block in re.findall(r"/\* ([\w-]+) \*/\s*(@font-face \{.*?\})", css, re.S):
        if subset not in ("latin", "latin-ext"): continue
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        style = re.search(r"font-style: (\w+)", block).group(1)
        weight = re.search(r"font-weight: ([\d ]+)", block).group(1).strip().replace(" ", "-")
        fn = f"{slug}-{style}-{weight}-{subset}.woff2"
        if not os.path.exists(fn):
            urllib.request.urlretrieve(url, fn)
        out.append(block.replace(url, fn))
open("fonts.css", "w").write("\n".join(out) + "\n")
for name, d in [("bricolage-grotesque","bricolagegrotesque"),("literata","literata"),("space-mono","spacemono")]:
    urllib.request.urlretrieve(f"https://raw.githubusercontent.com/google/fonts/main/ofl/{d}/OFL.txt", f"OFL-{name}.txt")
